import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Nav from "@/components/Nav";


export const metadata: Metadata = {
  title: "NPLCoder",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-verdana antialiased">
        <ThemeProvider>
        <Nav/>
        {children}</ThemeProvider>

      </body>
    </html>
  );
}
